# Generated by Django 3.2.8 on 2022-02-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_bcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='uploads/blogimg')),
                ('Summary', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.bcategories')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdetnew')),
            ],
        ),
    ]
