# Generated by Django 3.2.8 on 2022-02-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_bpost_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpost',
            name='Image',
            field=models.ImageField(upload_to='uploads/blogimg/'),
        ),
    ]
